Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -19,13 +19,15 @@ jobs:
         with:
           egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
 
-      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.07 with:
-        with:
-          persist-credentials: false
+      - uses: n80fr1n60/secure-checkout@c64cb640a80cda75c4172528782e3c79e05a58fd # v1.0.0      
       - name: Run a one-line script
-      
         run: echo Hello, world!
 
+      - name: Try to fetch with no credentials
+        run: |
+          set -x
+          git fetch || echo "Fetch failed as expected (no persisted credentials)"
+      
       - name: Setup Go
         uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
         with:
